import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'es' | 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    nav_home: 'Inicio',
    nav_solutions: 'Soluciones',
    nav_industries: 'Industrias',
    nav_process: 'Proceso',
    nav_about: 'Nosotros',
    nav_resources: 'Recursos',
    nav_contact: 'Contacto',
    hero_title: 'Puente confiable entre el Caribe y las fábricas de China',
    hero_subtitle: 'Negociamos, verificamos y entregamos equipos y materiales con costos optimizados y cero sorpresas.',
    cta_quote: 'Solicitar cotización',
    cta_process: 'Ver proceso',
    trust_hk: 'Hong Kong SAR',
    trust_rd: 'RD/Caribe',
    trust_incoterms: 'Incoterms',
    trust_qa: 'QA/QC',
    trust_contracts: 'Contratos bilingües',
    trust_inspection: 'Inspección de carga',
    solutions_title: 'Soluciones',
    solution_rfq_title: 'Compras a medida (RFQ)',
    solution_rfq_desc: 'Solicitudes personalizadas con especificaciones técnicas y requisitos exactos.',
    solution_audit_title: 'Auditoría y verificación de fábricas',
    solution_audit_desc: 'Verificación legal, capacidad, auditoría social y cumplimiento.',
    solution_quality_title: 'Control de calidad e inspección',
    solution_quality_desc: 'Pre-producción, during-production, pre-embarque con estándares AQL.',
    solution_logistics_title: 'Logística y aduanas (DR/Caribe)',
    solution_logistics_desc: 'Booking, seguros, documentación (BL, CI, PL), aduanas RD/Caribe.',
    solution_consolidation_title: 'Consolidación y carga mixta (LCL/FCL)',
    solution_consolidation_desc: 'Consolidación de pedidos de varios proveedores con control de calidad y lista de empaque unificada.',
    process_title: 'Proceso Hargna',
    process_step1: 'RFQ detallado',
    process_step2: 'Sourcing & verificación',
    process_step3: 'Cotización & contrato',
    process_step4: 'Producción & QA',
    process_step5: 'Logística & aduana',
    process_step6: 'Entrega & soporte',
    industries_title: 'Industrias',
    industries_subtitle: 'Enfoque inicial en sectores clave',
    industry_metal: 'Estructuras metálicas y prefabricados',
    industry_solar: 'Energía solar y eléctricos',
    industry_machinery: 'Maquinaria y equipos',
    industry_construction: 'Construcción',
    industry_cold: 'Refrigeración y climatización logística',
    cta_catalog: 'Pedir catálogo',
    case_study_title: 'Caso de éxito',
    case_study_kpi: '% ahorro, días de entrega, cero rechazos QA',
    cta_final: 'Cuéntanos tu necesidad y en 48h te enviamos opciones verificadas.',
    footer_company: 'Hargna Limited',
    footer_location: 'Hong Kong SAR',
    footer_rd: 'República Dominicana',
    about_title: 'Sobre Hargna',
    about_subtitle: 'Tu socio confiable entre el Caribe y China',
    about_text: 'Somos una empresa establecida en Hong Kong SAR con presencia local en República Dominicana y el Caribe. Nuestro equipo combina experiencia en comercio internacional, verificación de calidad y conocimiento profundo de regulaciones locales (ITBIS, DGA) y estándares Incoterms.',
    differentiators_title: 'Diferenciadores',
    diff_1: 'Fábricas verificadas + inspecciones independientes',
    diff_2: 'Contrato en español/inglés/chino con KPI de calidad',
    diff_3: 'Consolidación multimarca para bajar costos',
    diff_4: 'Experiencia local RD/Caribe (normativa, ITBIS, DGA)',
    contact_title: 'Contacto',
    contact_subtitle: 'Solicita tu cotización',
    form_company: 'Empresa',
    form_name: 'Nombre',
    form_email: 'Email',
    form_phone: 'Teléfono (WhatsApp)',
    form_products: 'Productos / Equipos que necesita',
    form_products_placeholder: 'Ej: Estructuras metálicas, paneles solares, maquinaria',
    form_specifications: 'Especificaciones técnicas',
    form_specifications_placeholder: 'Normas, estándares, HS Code, características técnicas',
    form_quantity: 'Cantidad estimada',
    form_quantity_placeholder: 'Ej: 100 unidades, 50 m², 20 toneladas',
    form_destination: 'Destino (Puerto/Aeropuerto)',
    form_destination_placeholder: 'Ej: Puerto Caucedo, Aeropuerto Las Américas',
    form_incoterm: 'Incoterm preferido',
    form_incoterm_select: 'Seleccione...',
    form_timeline: 'Plazo de entrega deseado',
    form_timeline_placeholder: 'Ej: 60 días, 3 meses',
    form_services: 'Servicios adicionales',
    form_inspection: 'Requiero inspección en origen',
    form_consolidation: 'Consolidación con otros pedidos',
    form_translation: 'Traducción técnica',
    form_additional: 'Información adicional',
    form_submit: 'Enviar solicitud',
    form_submitting: 'Enviando...',
    form_success: 'Solicitud enviada exitosamente. Nos contactaremos en 24-48h.',
    form_error: 'Error al enviar. Por favor intente nuevamente.',
    resources_title: 'Recursos',
    resources_subtitle: 'Guías, checklists y herramientas útiles',
    resource_incoterms_title: 'Guía de Incoterms',
    resource_incoterms_desc: 'Guía completa sobre Incoterms (EXW, FOB, CIF, DDP) y cómo elegir el más conveniente para tu operación.',
    resource_inspection_title: 'Checklist de Inspección',
    resource_inspection_desc: 'Lista de verificación para inspecciones de calidad pre-producción, during-production y pre-embarque.',
    resource_freight_title: 'Calculadora de Flete',
    resource_freight_desc: 'Herramienta para estimar costos de flete marítimo y aéreo desde China al Caribe.',
    resource_download: 'Solicitar descarga',
    faq_title: 'Preguntas Frecuentes',
    faq_q1: '¿Pueden consolidar pedidos de varios proveedores en un mismo contenedor?',
    faq_a1: 'Sí, coordinamos la consolidación LCL/FCL con control de calidad y lista de empaque unificada. Esto reduce costos de transporte significativamente.',
    faq_q2: '¿Trabajan con contratos con penalidades por calidad?',
    faq_a2: 'Sí, proponemos KPIs y remedios contractuales claros. Nuestros contratos incluyen cláusulas de calidad verificables con inspecciones independientes.',
    faq_q3: '¿Qué tipo de inspecciones realizan?',
    faq_a3: 'Realizamos inspecciones pre-producción, during-production (PSI) y pre-embarque (final inspection) siguiendo estándares AQL. Incluyen verificación de especificaciones técnicas, muestras y documentación.',
    faq_q4: '¿Cuál es el tiempo de respuesta para una cotización?',
    faq_a4: 'Recibimos tu RFQ y te enviamos opciones verificadas en 24-48 horas. Para productos complejos podría extenderse a 3-5 días.',
    faq_q5: '¿Manejan la documentación aduanal para República Dominicana?',
    faq_a5: 'Sí, coordinamos toda la documentación necesaria: BL (Bill of Lading), Commercial Invoice, Packing List, y certificados según producto. Conocemos los requisitos de ITBIS y DGA.',
    services_page_title: 'Puente confiable entre el Caribe y las fábricas de China',
    services_page_subtitle: 'Negociamos, verificamos y entregamos equipos y materiales con costos optimizados y cero sorpresas.',
    services_page_label: 'Nuestros servicios/',
    service_rfq: 'Compras a medida (RFQ)',
    service_rfq_short: 'Solicitudes personalizadas con especificaciones técnicas y requisitos exactos.',
    service_audit: 'Auditoría de fábricas',
    service_audit_short: 'Verificación legal, capacidad, auditoría social y cumplimiento.',
    service_quality: 'Control de calidad',
    service_quality_short: 'Pre-producción, during-production, pre-embarque con estándares AQL.',
    service_logistics: 'Logística y aduanas',
    service_logistics_short: 'Booking, seguros, documentación (BL, CI, PL), aduanas RD/Caribe.',
    service_consolidation: 'Consolidación de carga',
    service_consolidation_short: 'Consolidación de pedidos de varios proveedores con control de calidad.',
    service_contracts: 'Contratos bilingües',
    service_contracts_short: 'Contratos en español/inglés/chino con KPI de calidad y penalidades.',
    services_cta_title: '¿Listo para comenzar? Solicita tu cotización hoy.',
    services_cta_button: 'Solicitar cotización',
    hero_cta_quote: 'Solicitar cotización',
    hero_cta_services: 'Nuestros servicios',
    nav_home_label: 'Inicio',
    nav_about_label: 'Nosotros',
    nav_services_label: 'Servicios',
    nav_pages_label: 'Páginas',
    nav_contact_label: 'Contacto',
    nav_quote_button: 'Solicitar cotización',
    value_quality: 'Calidad',
    value_quality_desc: 'Compromiso con la excelencia',
    value_teamwork: 'Trabajo en equipo',
    value_teamwork_desc: 'Enfoque colaborativo',
    value_innovation: 'Innovación',
    value_innovation_desc: 'Soluciones líderes',
    value_growth: 'Crecimiento',
    value_growth_desc: 'Mejora continua',
    solutions_label: 'Lo que ofrecemos',
    solutions_subtitle: 'Soluciones integrales adaptadas para optimizar tus operaciones de abastecimiento desde China',
    solutions_learn_more: 'Conocer más',
    solutions_cta_title: '¿Listo para transformar tu abastecimiento?',
    solutions_cta_subtitle: 'Obtén una cotización personalizada adaptada a las necesidades de tu negocio y descubre cómo podemos acelerar tu crecimiento',
    solutions_cta_button: 'Comenzar hoy',
    contact_badge: 'Ponerse en contacto'
  },
  en: {
    nav_home: 'Home',
    nav_solutions: 'Solutions',
    nav_industries: 'Industries',
    nav_process: 'Process',
    nav_about: 'About',
    nav_resources: 'Resources',
    nav_contact: 'Contact',
    hero_title: 'A trusted bridge between the Caribbean and Chinese factories',
    hero_subtitle: 'We negotiate, verify, and deliver certified-quality materials and equipment with optimized costs—no surprises.',
    cta_quote: 'Request a quote',
    cta_process: 'See our process',
    trust_hk: 'Hong Kong SAR',
    trust_rd: 'RD/Caribbean',
    trust_incoterms: 'Incoterms',
    trust_qa: 'QA/QC',
    trust_contracts: 'Bilingual contracts',
    trust_inspection: 'Cargo inspection',
    solutions_title: 'Solutions',
    solution_rfq_title: 'Custom purchases (RFQ)',
    solution_rfq_desc: 'Personalized requests with technical specifications and exact requirements.',
    solution_audit_title: 'Factory audit and verification',
    solution_audit_desc: 'Legal verification, capacity, social audit, and compliance.',
    solution_quality_title: 'Quality control and inspection',
    solution_quality_desc: 'Pre-production, during-production, pre-shipment with AQL standards.',
    solution_logistics_title: 'Logistics and customs (DR/Caribbean)',
    solution_logistics_desc: 'Booking, insurance, documentation (BL, CI, PL), DR/Caribbean customs.',
    solution_consolidation_title: 'Consolidation and mixed cargo (LCL/FCL)',
    solution_consolidation_desc: 'Consolidation of orders from multiple suppliers with quality control and unified packing list.',
    process_title: 'Hargna Process',
    process_step1: 'Detailed RFQ',
    process_step2: 'Sourcing & verification',
    process_step3: 'Quote & contract',
    process_step4: 'Production & QA',
    process_step5: 'Logistics & customs',
    process_step6: 'Delivery & support',
    industries_title: 'Industries',
    industries_subtitle: 'Initial focus on key sectors',
    industry_metal: 'Metal structures and prefab',
    industry_solar: 'Solar energy and electrical',
    industry_machinery: 'Machinery and equipment',
    industry_construction: 'Construction',
    industry_cold: 'Refrigeration/Logistics HVAC',
    cta_catalog: 'Request catalog',
    case_study_title: 'Success story',
    case_study_kpi: '% savings, delivery days, zero QA rejections',
    cta_final: 'Tell us your needs and we\'ll send you verified options in 24-48h.',
    footer_company: 'Hargna Limited',
    footer_location: 'Hong Kong SAR',
    footer_rd: 'Dominican Republic',
    about_title: 'About Hargna',
    about_subtitle: 'Your reliable partner between the Caribbean and China',
    about_text: 'We are a company established in Hong Kong SAR with local presence in the Dominican Republic and the Caribbean. Our team combines experience in international trade, quality verification and deep knowledge of local regulations (ITBIS, DGA) and Incoterms standards.',
    differentiators_title: 'Differentiators',
    diff_1: 'Verified factories + independent inspections',
    diff_2: 'Spanish/English/Chinese contract with quality KPIs',
    diff_3: 'Multi-brand consolidation to reduce costs',
    diff_4: 'Local DR/Caribbean experience (regulations, ITBIS, DGA)',
    contact_title: 'Contact',
    contact_subtitle: 'Request your quote',
    form_company: 'Company',
    form_name: 'Name',
    form_email: 'Email',
    form_phone: 'Phone (WhatsApp)',
    form_products: 'Products / Equipment needed',
    form_products_placeholder: 'E.g.: Metal structures, solar panels, machinery',
    form_specifications: 'Technical specifications',
    form_specifications_placeholder: 'Standards, norms, HS Code, technical characteristics',
    form_quantity: 'Estimated quantity',
    form_quantity_placeholder: 'E.g.: 100 units, 50 m², 20 tons',
    form_destination: 'Destination (Port/Airport)',
    form_destination_placeholder: 'E.g.: Caucedo Port, Las Americas Airport',
    form_incoterm: 'Preferred Incoterm',
    form_incoterm_select: 'Select...',
    form_timeline: 'Desired delivery time',
    form_timeline_placeholder: 'E.g.: 60 days, 3 months',
    form_services: 'Additional services',
    form_inspection: 'Inspection required at origin',
    form_consolidation: 'Consolidation with other orders',
    form_translation: 'Technical translation',
    form_additional: 'Additional information',
    form_submit: 'Submit request',
    form_submitting: 'Submitting...',
    form_success: 'Request sent successfully. We will contact you in 24-48h.',
    form_error: 'Error sending. Please try again.',
    resources_title: 'Resources',
    resources_subtitle: 'Guides, checklists and useful tools',
    resource_incoterms_title: 'Incoterms Guide',
    resource_incoterms_desc: 'Complete guide on Incoterms (EXW, FOB, CIF, DDP) and how to choose the most suitable for your operation.',
    resource_inspection_title: 'Inspection Checklist',
    resource_inspection_desc: 'Checklist for pre-production, during-production and pre-shipment quality inspections.',
    resource_freight_title: 'Freight Calculator',
    resource_freight_desc: 'Tool to estimate sea and air freight costs from China to the Caribbean.',
    resource_download: 'Request download',
    faq_title: 'Frequently Asked Questions',
    faq_q1: 'Can you consolidate orders from multiple suppliers in one container?',
    faq_a1: 'Yes, we coordinate LCL/FCL consolidation with quality control and unified packing list. This significantly reduces transportation costs.',
    faq_q2: 'Do you work with contracts with quality penalties?',
    faq_a2: 'Yes, we propose clear KPIs and contractual remedies. Our contracts include verifiable quality clauses with independent inspections.',
    faq_q3: 'What type of inspections do you perform?',
    faq_a3: 'We perform pre-production, during-production (PSI) and pre-shipment (final inspection) following AQL standards. They include verification of technical specifications, samples and documentation.',
    faq_q4: 'What is the response time for a quote?',
    faq_a4: 'We receive your RFQ and send you verified options in 24-48 hours. For complex products it could extend to 3-5 days.',
    faq_q5: 'Do you handle customs documentation for the Dominican Republic?',
    faq_a5: 'Yes, we coordinate all necessary documentation: BL (Bill of Lading), Commercial Invoice, Packing List, and product-specific certificates. We know the ITBIS and DGA requirements.',
    services_page_title: 'A trusted bridge between the Caribbean and Chinese factories',
    services_page_subtitle: 'We negotiate, verify, and deliver certified-quality materials and equipment with optimized costs—no surprises.',
    services_page_label: 'Our services/',
    service_rfq: 'Custom purchases (RFQ)',
    service_rfq_short: 'Personalized requests with technical specifications and exact requirements.',
    service_audit: 'Factory audit',
    service_audit_short: 'Legal verification, capacity, social audit, and compliance.',
    service_quality: 'Quality control',
    service_quality_short: 'Pre-production, during-production, pre-shipment with AQL standards.',
    service_logistics: 'Logistics and customs',
    service_logistics_short: 'Booking, insurance, documentation (BL, CI, PL), DR/Caribbean customs.',
    service_consolidation: 'Cargo consolidation',
    service_consolidation_short: 'Consolidation of orders from multiple suppliers with quality control.',
    service_contracts: 'Bilingual contracts',
    service_contracts_short: 'Spanish/English/Chinese contracts with quality KPIs and penalties.',
    services_cta_title: 'Ready to get started? Request your quote today.',
    services_cta_button: 'Get a quote',
    hero_cta_quote: 'Get a Quote',
    hero_cta_services: 'Our Services',
    nav_home_label: 'Home',
    nav_about_label: 'About',
    nav_services_label: 'Services',
    nav_pages_label: 'Pages',
    nav_contact_label: 'Contact',
    nav_quote_button: 'Get a Quote',
    value_quality: 'Quality',
    value_quality_desc: 'Commitment to excellence',
    value_teamwork: 'Teamwork',
    value_teamwork_desc: 'Collaborative approach',
    value_innovation: 'Innovation',
    value_innovation_desc: 'Leading solutions',
    value_growth: 'Growth',
    value_growth_desc: 'Continuous improvement',
    solutions_label: 'What We Offer',
    solutions_subtitle: 'Comprehensive solutions tailored to streamline your China sourcing operations',
    solutions_learn_more: 'Learn more',
    solutions_cta_title: 'Ready to Transform Your Sourcing?',
    solutions_cta_subtitle: 'Get a customized quote tailored to your business needs and discover how we can accelerate your growth',
    solutions_cta_button: 'Get Started Today',
    contact_badge: 'Get in Touch'
  },
  zh: {
    nav_home: '首页',
    nav_solutions: '解决方案',
    nav_industries: '行业',
    nav_process: '流程',
    nav_about: '关于我们',
    nav_resources: '资源',
    nav_contact: '联系',
    hero_title: '加勒比与中国工厂之间的可靠桥梁',
    hero_subtitle: '我们谈判、验证并交付经过认证的优质材料和设备，成本优化——无意外。',
    cta_quote: '询价',
    cta_process: '查看流程',
    trust_hk: '香港特别行政区',
    trust_rd: '多米尼加/加勒比',
    trust_incoterms: '国际贸易术语',
    trust_qa: '质量保证/质量控制',
    trust_contracts: '双语合同',
    trust_inspection: '货物检验',
    solutions_title: '解决方案',
    solution_rfq_title: '定制采购（RFQ）',
    solution_rfq_desc: '具有技术规格和确切要求的个性化请求。',
    solution_audit_title: '工厂审核和验证',
    solution_audit_desc: '法律验证、产能、社会审核和合规性。',
    solution_quality_title: '质量控制和检验',
    solution_quality_desc: '生产前、生产中、装运前的AQL标准检验。',
    solution_logistics_title: '物流和海关（多米尼加/加勒比）',
    solution_logistics_desc: '订舱、保险、文件（提单、商业发票、装箱单）、多米尼加/加勒比海关。',
    solution_consolidation_title: '整合和混合货物（LCL/FCL）',
    solution_consolidation_desc: '来自多个供应商的订单整合，具有质量控制和统一装箱单。',
    process_title: 'Hargna 流程',
    process_step1: '详细询价',
    process_step2: '采购与验证',
    process_step3: '报价与合同',
    process_step4: '生产与质量保证',
    process_step5: '物流与海关',
    process_step6: '交付与支持',
    industries_title: '行业',
    industries_subtitle: '重点关注关键行业',
    industry_metal: '金属结构和预制件',
    industry_solar: '太阳能和电气',
    industry_machinery: '机械和设备',
    industry_construction: '建筑',
    industry_cold: '制冷/物流暖通空调',
    cta_catalog: '索取目录',
    case_study_title: '成功案例',
    case_study_kpi: '节省百分比、交付天数、零质量拒绝',
    cta_final: '告诉我们您的需求，我们会在24-48小时内向您发送经过验证的选项。',
    footer_company: 'Hargna Limited',
    footer_location: '香港特别行政区',
    footer_rd: '多米尼加共和国',
    about_title: '关于Hargna',
    about_subtitle: '您在加勒比与中国之间的可靠合作伙伴',
    about_text: '我们是一家在香港特别行政区注册的公司，在多米尼加共和国和加勒比地区设有本地办事处。我们的团队结合了国际贸易经验、质量验证以及对当地法规（ITBIS、DGA）和国际贸易术语标准的深刻了解。',
    differentiators_title: '差异化优势',
    diff_1: '经过验证的工厂+独立检验',
    diff_2: '西班牙语/英语/中文合同，具有质量KPI',
    diff_3: '多品牌整合以降低成本',
    diff_4: '本地多米尼加/加勒比经验（法规、ITBIS、DGA）',
    contact_title: '联系我们',
    contact_subtitle: '索取报价',
    form_company: '公司',
    form_name: '姓名',
    form_email: '电子邮件',
    form_phone: '电话（WhatsApp）',
    form_products: '所需产品/设备',
    form_products_placeholder: '例如：金属结构、太阳能电池板、机械',
    form_specifications: '技术规格',
    form_specifications_placeholder: '标准、规范、HS代码、技术特性',
    form_quantity: '估计数量',
    form_quantity_placeholder: '例如：100件、50平方米、20吨',
    form_destination: '目的地（港口/机场）',
    form_destination_placeholder: '例如：考塞多港、美洲机场',
    form_incoterm: '首选国际贸易术语',
    form_incoterm_select: '选择...',
    form_timeline: '期望交付时间',
    form_timeline_placeholder: '例如：60天、3个月',
    form_services: '附加服务',
    form_inspection: '需要原产地检验',
    form_consolidation: '与其他订单合并',
    form_translation: '技术翻译',
    form_additional: '附加信息',
    form_submit: '提交请求',
    form_submitting: '提交中...',
    form_success: '请求已成功发送。我们将在24-48小时内与您联系。',
    form_error: '发送错误。请重试。',
    resources_title: '资源',
    resources_subtitle: '指南、清单和有用工具',
    resource_incoterms_title: '国际贸易术语指南',
    resource_incoterms_desc: '关于国际贸易术语（EXW、FOB、CIF、DDP）的完整指南以及如何选择最适合您操作的术语。',
    resource_inspection_title: '检验清单',
    resource_inspection_desc: '生产前、生产中和装运前质量检验的清单。',
    resource_freight_title: '运费计算器',
    resource_freight_desc: '估算从中国到加勒比的海运和空运成本的工具。',
    resource_download: '请求下载',
    faq_title: '常见问题',
    faq_q1: '您能将多个供应商的订单合并到一个集装箱中吗？',
    faq_a1: '是的，我们协调LCL/FCL合并，进行质量控制和统一装箱单。这大大降低了运输成本。',
    faq_q2: '您是否使用具有质量处罚条款的合同？',
    faq_a2: '是的，我们提出明确的KPI和合同补救措施。我们的合同包括可通过独立检验验证的质量条款。',
    faq_q3: '您进行什么类型的检验？',
    faq_a3: '我们按照AQL标准进行生产前、生产中（PSI）和装运前（最终检验）检验。包括技术规格、样品和文件的验证。',
    faq_q4: '报价的响应时间是多长？',
    faq_a4: '我们收到您的询价后，会在24-48小时内向您发送经过验证的选项。对于复杂产品，可能需要3-5天。',
    faq_q5: '您处理多米尼加共和国的海关文件吗？',
    faq_a5: '是的，我们协调所有必要的文件：提单（BL）、商业发票、装箱单和产品特定证书。我们了解ITBIS和DGA的要求。',
    services_page_title: '加勒比与中国工厂之间的可靠桥梁',
    services_page_subtitle: '我们谈判、验证并交付经过认证的优质材料和设备，成本优化——无意外。',
    services_page_label: '我们的服务/',
    service_rfq: '定制采购（RFQ）',
    service_rfq_short: '具有技术规格和确切要求的个性化请求。',
    service_audit: '工厂审核',
    service_audit_short: '法律验证、产能、社会审核和合规性。',
    service_quality: '质量控制',
    service_quality_short: '生产前、生产中、装运前的AQL标准检验。',
    service_logistics: '物流和海关',
    service_logistics_short: '订舱、保险、文件（提单、商业发票、装箱单）、多米尼加/加勒比海关。',
    service_consolidation: '货物整合',
    service_consolidation_short: '来自多个供应商的订单整合，具有质量控制。',
    service_contracts: '双语合同',
    service_contracts_short: '西班牙语/英语/中文合同，具有质量KPI和处罚。',
    services_cta_title: '准备好开始了吗？立即索取报价。',
    services_cta_button: '索取报价',
    hero_cta_quote: '索取报价',
    hero_cta_services: '我们的服务',
    nav_home_label: '首页',
    nav_about_label: '关于我们',
    nav_services_label: '服务',
    nav_pages_label: '页面',
    nav_contact_label: '联系',
    nav_quote_button: '索取报价',
    value_quality: '质量',
    value_quality_desc: '致力于卓越',
    value_teamwork: '团队合作',
    value_teamwork_desc: '协作方法',
    value_innovation: '创新',
    value_innovation_desc: '领先解决方案',
    value_growth: '增长',
    value_growth_desc: '持续改进',
    solutions_label: '我们提供的服务',
    solutions_subtitle: '为优化您的中国采购业务量身定制的综合解决方案',
    solutions_learn_more: '了解更多',
    solutions_cta_title: '准备好改变您的采购方式了吗？',
    solutions_cta_subtitle: '获取根据您的业务需求定制的报价，了解我们如何加速您的增长',
    solutions_cta_button: '立即开始',
    contact_badge: '联系我们'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('hargna_language');
    return (savedLanguage as Language) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('hargna_language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
